name: "Setup"
description: "Checkout the repository and setup Node.js environment"

runs:
  using: composite
  steps:
    - name: Checkout code repository
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
