extends: ["@ocavue/eslint-config-react"]
settings:
  react:
    version: "18"
rules:
  no-useless-escape: off
  no-console: [error, { allow: [warn, error, log, assert] }]

  react-hooks/exhaustive-deps:
    - warn
    - enableDangerousAutofixThisMayCauseInfiniteLoops: true

  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-empty-method": off
