root: true
parser: "@typescript-eslint/parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: 2018 # Allows for the parsing of modern ECMAScript features
  project: ["./tsconfig.json"]
  tsconfigRootDir: '.'
  ecmaFeatures:
    jsx: true
extends:
  # https://github.com/typescript-eslint/typescript-eslint/tree/v2.25.0/packages/eslint-plugin#recommended-configs
  - "eslint:recommended" # the set of rules which are recommended for all projects by the ESLint Team
  - "plugin:@typescript-eslint/recommended" # recommended rules for typescript
  - "plugin:@typescript-eslint/recommended-requiring-type-checking" # provide lint rules with access to type information

  # https://www.npmjs.com/package/eslint-plugin-react
  - "plugin:react/recommended"

  # https://www.npmjs.com/package/eslint-plugin-react-hooks
  - "plugin:react-hooks/recommended"

  # runs Prettier as an ESLint rule
  - "plugin:prettier/recommended"

  # turns off all ELLint rules that are unnecessary or might conflict with Prettier
  - "prettier"
  - "prettier/@typescript-eslint" # for @typescript-eslint/eslint-plugin
  - "prettier/react" # for eslint-plugin-react
plugins:
  - "simple-import-sort"
settings:
  react:
    version: "detect" # Tells eslint-plugin-react to automatically detect the version of React to use
env:
  browser: true
  node: true
rules:
  "no-useless-escape": "off"

  "react/prop-types": [1, { skipUndeclared: true }]
  "react/no-unescaped-entities": "off"

  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/no-unused-vars": [error, { args: "none" }]
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-empty-function": "off"

  # use `simple-import-sort` to sort import
  "sort-imports": "off"
  "simple-import-sort/sort":
    - "error"
    - groups: [
      # Side effect imports.
      ["^\\u0000"],
      # Packages.
      # Things that start with a letter (or digit or underscore), or `@` followed by a letter.
      ["^@?\\w"],
      # Absolute imports and other imports such as Vue-style `@/foo`.
      # Anything that does not start with a dot.
      ["^[^.]"],
      # Absolute imports based on tsconfig.json's `baseUrl`.
      # Check https://github.com/lydell/eslint-plugin-simple-import-sort/issues/31 for more information.
      # Anything that start with `src/`, `config/` or `tests/`
      ["^(?:src|config|tests)\/"],
      # Relative imports.
      # Anything that starts with a dot.
      ["^\\."],
    ]
overrides:
  - files:
      - "tests/**/*"
      - "**/__test__/*"
    env:
      jest: true
    extends:
      - "plugin:jest/style"
      - "plugin:jest/recommended"
    rules:
      "jest/expect-expect": "off"
    globals:
      page: "readonly"
      browser: "readonly"
      context: "readonly"
      jestPuppeteer: "readonly"
  - files: "scripts/*"
    rules:
      "@typescript-eslint/no-var-requires": off
ignorePatterns:
  - jest*.js
  - node_modules/
  - .next/
  - .dist/
