root: true
parser: vue-eslint-parser
parserOptions:
    parser: "@typescript-eslint/parser"
    ecmaVersion: 2018 # Allows for the parsing of modern ECMAScript features
    project: "./tsconfig.json"
extends:
    - "plugin:vue/recommended"
    - "plugin:@typescript-eslint/recommended-requiring-type-checking"
    - "@vue/typescript/recommended"
    - "@vue/prettier/recommended"
    - "@vue/prettier/@typescript-eslint"
env:
    browser: true
    node: true
rules:
    "no-console": "off"
    "no-unused-vars": [error, { args: "none" }]
    "no-useless-escape": "off"
    "@typescript-eslint/explicit-function-return-type": "off"
    "@typescript-eslint/no-explicit-any": "off"
    "@typescript-eslint/no-unused-vars": [error, { args: "none" }]
    "@typescript-eslint/no-empty-function": "off"

overrides:
    - files: "tests/**/*.[t|j]s"
      env:
          jest: true
      globals:
          page: "readonly"
          browser: "readonly"
          context: "readonly"
          jestPuppeteer: "readonly"
