root: true
parser: vue-eslint-parser
parserOptions:
    parser: "@typescript-eslint/parser"
    ecmaVersion: 2018 # Allows for the parsing of modern ECMAScript features
plugins:
    - "@typescript-eslint"
    - "prettier"
extends:
    - "plugin:@typescript-eslint/recommended"
    - "plugin:vue/recommended"
    - "plugin:prettier/recommended"
    # Uses "eslint-config-prettier" to disable ESLint rules from "@typescript-eslint/eslint-plugin" and "eslint-plugin-vue" that would conflict with prettier
    - "prettier/@typescript-eslint"
    - "@vue/prettier"
    - "@vue/typescript"
env:
    browser: true
    node: true
    jest: true
rules:
    "no-console": "off"
    "no-useless-escape": "off"
    "@typescript-eslint/explicit-function-return-type": "off"
    "@typescript-eslint/no-explicit-any": "off"
    "@typescript-eslint/no-unused-vars": [error, { args: "none" }]
