# https://prettier.io/docs/en/configuration.html
# https://prettier.io/docs/en/options.html
semi: false
tabWidth: 4
trailingComma: all
printWidth: 140
overrides:
  - files: ["*.yaml", "*.yml"]
    options:
      tabWidth: 2
