# https://prettier.io/docs/en/configuration.html
# https://prettier.io/docs/en/options.html
semi: false
tabWidth: 4
trailingComma: "all"
printWidth: 100
overrides:
  - files: "cypress/**/*.ts"
    options:
      tabWidth: 2
