codecov:
  # Should Codecov wait for all other statues to pass before sending it's status.
  # Type: Boolean
  # Default: yes
  require_ci_to_pass: no

  status:
    project:
      default:
        target: auto # auto % coverage target
        threshold: 5%  # allow for 5% reduction of coverage without failing
