# Run the follow command to validate this file
# curl --data-binary @codecov.yml https://codecov.io/validate

# You need to install Codecov's GitHub App ( https://github.com/apps/codecov ) to use some feature.

codecov:
  # Should Codecov wait for all other statues to pass before sending it's status.
  # Type: Boolean
  # Default: yes
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        threshold: 1%  # allow for X% reduction of coverage without failing
    patch: off
