"use strict";
exports.__esModule = true;
var add_column_after_svg_1 = require("../../../../src/assets/add_column_after.svg");
exports.AddColumnAfter = add_column_after_svg_1["default"];
var add_column_before_svg_1 = require("../../../../src/assets/add_column_before.svg");
exports.AddColumnBefore = add_column_before_svg_1["default"];
var add_row_after_svg_1 = require("../../../../src/assets/add_row_after.svg");
exports.AddRowAfter = add_row_after_svg_1["default"];
var add_row_before_svg_1 = require("../../../../src/assets/add_row_before.svg");
exports.AddRowBefore = add_row_before_svg_1["default"];
var delete_column_svg_1 = require("../../../../src/assets/delete_column.svg");
exports.DeleteColumn = delete_column_svg_1["default"];
var delete_row_svg_1 = require("../../../../src/assets/delete_row.svg");
exports.DeleteRow = delete_row_svg_1["default"];
