name: main

on:
  push:
    branches:
      - "**"

env:
  NEXT_TELEMETRY_DISABLED: 1 # https://nextjs.org/telemetry

jobs:
  build_website:
    runs-on: ubuntu-18.04
    steps:
      - &step_checkout
        name: Checkout code repository
        uses: actions/checkout@v2

      - &step_setup_node
        name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - &step_cache_deps
        id: step_cache_deps
        name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/firebase
            ~/.cache/ms-playwright
            .yarn/cache
          key: ${{ runner.os }}-deps-v6-${{ hashFiles('yarn.lock') }}

      - &step_install_deps
        name: Install Dependencies
        # Reinstall node modules even if `cache-hit` is `true` because we need to build symlinks for Yarn workspace
        run: |
          date
          yarn install --immutable
          date
          echo "[DEBUG] CACHE_HIT: $CACHE_HIT"
          sudo ln -sf $PWD/node_modules/.bin/ultra /usr/local/bin/ultra
        env:
          CACHE_HIT: ${{ steps.step_cache_deps.outputs.cache-hit }}

      - name: Build website
        run: |
          ultra exec home build

      - name: Upload dist (home)
        uses: actions/upload-artifact@v2
        with:
          name: home_dist
          path: ./packages/home/dist

  build_electron:
    runs-on: macos-10.15
    steps:
      - *step_checkout
      - *step_setup_node
      - *step_cache_deps
      - *step_install_deps

      - name: Update package.json
        run: |
          version=$(cat version.txt)
          pkgjson=$(jq ".version = \"$version\"" ./packages/electron/package.json)
          echo "$pkgjson" > ./packages/electron/package.json
          cat ./packages/electron/package.json

      - name: Build dependencies
        run: |
          ultra exec editor build

        # I have to use yarn install of ultra because electron-builder will detect which
        # package manager I'm using and have differernt behaviors.
      - name: Build electron
        run: |
          cd packages/electron
          yarn run build

      - name: Clean electron dist
        run: |
          cd packages/electron
          find ./dist -type f
          yarn run clean

      - name: Upload dist (electron)
        uses: actions/upload-artifact@v2
        with:
          name: electron_dist
          path: ./packages/electron/dist

  test:
    runs-on: ubuntu-18.04
    steps:
      - *step_checkout
      - *step_setup_node
      - *step_cache_deps
      - *step_install_deps

      - name: Build dependencies
        env:
          REACT_APP_TEST_USERNAME: ${{ secrets.REACT_APP_TEST_USERNAME }}
          REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
          REACT_APP_TESTING: 1
        run: |
          ultra exec common build
          ultra exec next build

      - name: Run tests
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # https://firebase.google.com/docs/cli#cli-ci-systems
          REACT_APP_TEST_USERNAME: ${{ secrets.REACT_APP_TEST_USERNAME }}
          REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
        run: |
          ultra test --coverage

      - name: Upload coverage information to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: false # Specify if CI pipeline should fail when Codecov runs into errors during upload. Defaults to false

  lint:
    runs-on: ubuntu-18.04
    steps:
      - *step_checkout
      - *step_setup_node
      - *step_cache_deps
      - *step_install_deps

      - name: Check files
        run: ls ./packages/**/dist/ || true

      - name: Lint
        run: ultra lint .

      - name: Check actions configration
        run: |
          hash1=$(sha1sum .github/workflows/main.yml)
          ./node_modules/.bin/js-yaml .github/temp/main.yml > .github/workflows/main.yml
          hash2=$(sha1sum .github/workflows/main.yml)
          echo "$hash1" "$hash2"
          if [ "$hash1" != "$hash2" ]; then exit 1; fi

  preview: # Preview deployment
    runs-on: ubuntu-18.04
    steps:
      - *step_checkout
      - *step_setup_node
      - *step_cache_deps
      - *step_install_deps

      - name: Build
        run: |
          ultra exec home build

      - id: step_branch
        name: Get the branch name
        run: |
          echo "::set-output name=branch::$(node scripts/slugify-branch.js)"

      - name: Deploy @rino.app/home to Vercel
        uses: &vercel_action amondnet/vercel-action@v20
        timeout-minutes: 10
        with: &vercel_args
          github-comment: false
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
          alias-domains: rino-home-${{ steps.step_branch.outputs.branch }}.ocavue.vercel.app
          vercel-args: '--meta TYPE=PREVIEW'
          working-directory: './packages/home/'

      - uses: jwalton/gh-find-current-pr@v1
        id: step_find_pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.step_find_pr.outputs.pr }}
          message: |
            ## Preview Deployment
            ${{ github.sha }}:
            - https://rino-home-${{ steps.step_branch.outputs.branch }}.ocavue.vercel.app
        continue-on-error: true

      - name: Generate configrations for Lighthouse CI
        run: node scripts/generate-lighthouserc.js

      - name: Run lighthouse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Install this GitHub App and get the token: https://github.com/apps/lighthouse-ci
        run: |
          ultra lhci autorun --config .lighthouserc.home.json

  release:
    runs-on: ubuntu-18.04
    needs:
      - build_website
      - build_electron
      - test
      - lint
      - preview
    if: github.ref == 'refs/heads/master'
    steps:
      - id: step_release_please
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          release-type: simple

    outputs:
      published: ${{ steps.step_release_please.outputs.release_created }}
      tag_name: ${{ steps.step_release_please.outputs.tag_name }}

  deployment: # Production deployment
    runs-on: ubuntu-18.04
    needs:
      - release
    if: github.ref == 'refs/heads/master' && ( needs.release.outputs.published == 'true' || contains(github.event.head_commit.message, '[force-deploy]') )
    steps:
      - *step_checkout
      - *step_setup_node

      - &step_download_home_dist
        name: Download dist (home)
        uses: actions/download-artifact@v2
        with:
          name: home_dist
          path: ./packages/home/dist

      - &step_download_electron_dist
        name: Download dist (electron)
        uses: actions/download-artifact@v2
        with:
          name: electron_dist
          path: ./packages/electron/dist

      - name: Upload @rino.app/electron to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./packages/electron/dist/*
          tag: ${{ needs.release.outputs.tag_name }}
          overwrite: true
          file_glob: true

      - name: Deploy @rino.app/home to Vercel
        uses: *vercel_action
        with:
          <<: *vercel_args
          alias-domains: rino-home-master.ocavue.vercel.app
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
          vercel-args: '--prod --meta TYPE=PRODUCTION'
          working-directory: './packages/home/'
