name: "Install dependencies"
description: "Install dependencies"

runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        run_install: false

    - id: step_pnpm_cache
      name: Get pnpm store directory
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      shell: bash

    - id: step_cache_deps
      name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.step_pnpm_cache.outputs.pnpm_cache_dir }}
          ~/cache_electron
          ~/cache_electron_builder
          ~/cache_playwright_browsers

        key: ${{ runner.os }}-deps-v31-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Setup cache directory
      run: |
        echo "ELECTRON_CACHE=$HOME/cache_electron" >> $GITHUB_ENV
        echo "ELECTRON_BUILDER_CACHE=$HOME/cache_electron_builder" >> $GITHUB_ENV
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/cache_playwright_browsers" >> $GITHUB_ENV
      shell: bash

    - name: Print debug information
      run: |
        echo "[DEBUG] CACHE_HIT: $CACHE_HIT"
        echo "[DEBUG] GITHUB_REF: $GITHUB_REF"
        env | egrep '^ELECTRON_'
        du -h -d 1 ~/cache_* || true
      env:
        CACHE_HIT: ${{ steps.step_cache_deps.outputs.cache-hit }}
      shell: bash

    - name: Install dependencies
      run: pnpm install --loglevel debug --reporter append-only
      shell: bash
