name: "Install dependencies"
description: "Install dependencies"

runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - id: step_cache_deps
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          ~/cache_electron
          ~/cache_electron_builder
          ~/cache_playwright_browsers

        key: ${{ runner.os }}-deps-v25-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Setup cache directory
      run: |
        echo "ELECTRON_CACHE=$HOME/cache_electron" >> $GITHUB_ENV
        echo "ELECTRON_BUILDER_CACHE=$HOME/cache_electron_builder" >> $GITHUB_ENV
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/cache_playwright_browsers" >> $GITHUB_ENV
      shell: bash

    - name: Print debug information
      run: |
        echo "[DEBUG] CACHE_HIT: ${{ inputs.cache-hit }}"
        echo "[DEBUG] GITHUB_REF: $GITHUB_REF"
        env | egrep '^ELECTRON_'
        du -h -d 1 ~/cache_* || true
      env:
        CACHE_HIT: ${{ steps.step_cache_deps.outputs.cache-hit }}
      shell: bash

    - name: Install rush
      run: node common/scripts/install-run-rush.js
      shell: bash

    - name: Install pnpm dependencies
      run: rush install
      shell: bash

