name: "size"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: andresz1/size-limit-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     build_script: build:website
