name: update-deps

on:
  push:
    branches:
      - "renovate/dependencies*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - id: step_find_pr
        name: Find pull request
        uses: jwalton/gh-find-current-pr@v1

      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Install pnpm
        run: npm install -g pnpm
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Install dependencies
        run: pnpm install --ignore-scripts
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Update dependencies
        run: pnpm update-deps
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Push to GitHub
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(deps): update dependencies"
          git push
        if: ${{ steps.step_find_pr.outputs.number }}
