name: update-deps

on:
  push:
    branches:
      - "renovate/*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - id: step_find_pr
        name: Find pull request
        uses: jwalton/gh-find-current-pr@v1

      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Enable Corepack
        run: |
          corepack enable
          pnpm --version

      - name: Regenerate the lock file
        continue-on-error: true
        run: |
          if $(git log -1 --pretty=format:'%an' | egrep -q 'Renovate'); then
            echo "Regenerating lock file"
            rm -rf pnpm-lock.yaml
            pnpm i
            cd packages/rig
            pnpm output-licenses
          else
            echo "Skipping lockfile regeneration"
          fi
        if: ${{ steps.step_find_pr.outputs.number }}

      - name: Push to GitHub
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(deps): update all pnpm dependencies"
          git push
        if: ${{ steps.step_find_pr.outputs.number }}
