name: update-deps

on:
  push:
    branches:
      - "renovate/*"

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Update dependencies
        run: pnpm update-deps

      - name: Push to GitHub
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(deps): update dependencies"
          git push
